import type { Country } from '../../types';

export const countries: Country[] = [
  // ── Africa ──────────────────────────────────────────────────────────────
  { code: 'DZ', name: 'Algeria', region: 'Africa', fakerLocale: 'ar' },
  { code: 'AO', name: 'Angola', region: 'Africa' },
  { code: 'BJ', name: 'Benin', region: 'Africa', fakerLocale: 'fr' },
  { code: 'BW', name: 'Botswana', region: 'Africa', fakerLocale: 'en_ZA' },
  { code: 'BF', name: 'Burkina Faso', region: 'Africa', fakerLocale: 'fr' },
  { code: 'BI', name: 'Burundi', region: 'Africa', fakerLocale: 'fr' },
  { code: 'CV', name: 'Cabo Verde', region: 'Africa', fakerLocale: 'pt_PT' },
  { code: 'CM', name: 'Cameroon', region: 'Africa', fakerLocale: 'fr' },
  { code: 'CF', name: 'Central African Republic', region: 'Africa', fakerLocale: 'fr' },
  { code: 'TD', name: 'Chad', region: 'Africa', fakerLocale: 'fr' },
  { code: 'KM', name: 'Comoros', region: 'Africa', fakerLocale: 'ar' },
  { code: 'CG', name: 'Congo (Republic)', region: 'Africa', fakerLocale: 'fr' },
  { code: 'CD', name: 'Congo (DRC)', region: 'Africa', fakerLocale: 'fr' },
  { code: 'DJ', name: 'Djibouti', region: 'Africa', fakerLocale: 'ar' },
  { code: 'EG', name: 'Egypt', region: 'Africa', fakerLocale: 'ar' },
  { code: 'GQ', name: 'Equatorial Guinea', region: 'Africa', fakerLocale: 'es' },
  { code: 'ER', name: 'Eritrea', region: 'Africa' },
  { code: 'SZ', name: 'Eswatini', region: 'Africa', fakerLocale: 'en_ZA' },
  { code: 'ET', name: 'Ethiopia', region: 'Africa' },
  { code: 'GA', name: 'Gabon', region: 'Africa', fakerLocale: 'fr' },
  { code: 'GM', name: 'Gambia', region: 'Africa', fakerLocale: 'en_NG' },
  { code: 'GH', name: 'Ghana', region: 'Africa', fakerLocale: 'en_GH' },
  { code: 'GN', name: 'Guinea', region: 'Africa', fakerLocale: 'fr' },
  { code: 'GW', name: 'Guinea-Bissau', region: 'Africa', fakerLocale: 'pt_PT' },
  { code: 'CI', name: "Côte d'Ivoire", region: 'Africa', fakerLocale: 'fr' },
  { code: 'KE', name: 'Kenya', region: 'Africa', fakerLocale: 'en_NG' },
  { code: 'LS', name: 'Lesotho', region: 'Africa', fakerLocale: 'en_ZA' },
  { code: 'LR', name: 'Liberia', region: 'Africa' },
  { code: 'LY', name: 'Libya', region: 'Africa', fakerLocale: 'ar' },
  { code: 'MG', name: 'Madagascar', region: 'Africa', fakerLocale: 'fr' },
  { code: 'MW', name: 'Malawi', region: 'Africa', fakerLocale: 'en_NG' },
  { code: 'ML', name: 'Mali', region: 'Africa', fakerLocale: 'fr' },
  { code: 'MR', name: 'Mauritania', region: 'Africa', fakerLocale: 'ar' },
  { code: 'MU', name: 'Mauritius', region: 'Africa', fakerLocale: 'fr' },
  { code: 'MA', name: 'Morocco', region: 'Africa', fakerLocale: 'ar' },
  { code: 'MZ', name: 'Mozambique', region: 'Africa', fakerLocale: 'pt_PT' },
  { code: 'NA', name: 'Namibia', region: 'Africa', fakerLocale: 'en_ZA' },
  { code: 'NE', name: 'Niger', region: 'Africa', fakerLocale: 'fr' },
  { code: 'NG', name: 'Nigeria', region: 'Africa', fakerLocale: 'en_NG' },
  { code: 'RW', name: 'Rwanda', region: 'Africa', fakerLocale: 'fr' },
  { code: 'ST', name: 'São Tomé and Príncipe', region: 'Africa', fakerLocale: 'pt_PT' },
  { code: 'SN', name: 'Senegal', region: 'Africa', fakerLocale: 'fr' },
  { code: 'SC', name: 'Seychelles', region: 'Africa', fakerLocale: 'fr' },
  { code: 'SL', name: 'Sierra Leone', region: 'Africa', fakerLocale: 'en_NG' },
  { code: 'SO', name: 'Somalia', region: 'Africa', fakerLocale: 'ar' },
  { code: 'ZA', name: 'South Africa', region: 'Africa', fakerLocale: 'en_ZA' },
  { code: 'SS', name: 'South Sudan', region: 'Africa' },
  { code: 'SD', name: 'Sudan', region: 'Africa', fakerLocale: 'ar' },
  { code: 'TZ', name: 'Tanzania', region: 'Africa', fakerLocale: 'en_NG' },
  { code: 'TG', name: 'Togo', region: 'Africa', fakerLocale: 'fr' },
  { code: 'TN', name: 'Tunisia', region: 'Africa', fakerLocale: 'ar' },
  { code: 'UG', name: 'Uganda', region: 'Africa', fakerLocale: 'en_NG' },
  { code: 'ZM', name: 'Zambia', region: 'Africa', fakerLocale: 'en_ZA' },
  { code: 'ZW', name: 'Zimbabwe', region: 'Africa', fakerLocale: 'en_ZA' },

  // ── Americas ─────────────────────────────────────────────────────────────
  { code: 'AG', name: 'Antigua and Barbuda', region: 'Americas' },
  { code: 'AR', name: 'Argentina', region: 'Americas', fakerLocale: 'es' },
  { code: 'BS', name: 'Bahamas', region: 'Americas' },
  { code: 'BB', name: 'Barbados', region: 'Americas' },
  { code: 'BZ', name: 'Belize', region: 'Americas', fakerLocale: 'es' },
  { code: 'BO', name: 'Bolivia', region: 'Americas', fakerLocale: 'es' },
  { code: 'BR', name: 'Brazil', region: 'Americas', fakerLocale: 'pt_BR' },
  { code: 'CA', name: 'Canada', region: 'Americas', fakerLocale: 'en_CA' },
  { code: 'CL', name: 'Chile', region: 'Americas', fakerLocale: 'es' },
  { code: 'CO', name: 'Colombia', region: 'Americas', fakerLocale: 'es' },
  { code: 'CR', name: 'Costa Rica', region: 'Americas', fakerLocale: 'es' },
  { code: 'CU', name: 'Cuba', region: 'Americas', fakerLocale: 'es' },
  { code: 'DM', name: 'Dominica', region: 'Americas' },
  { code: 'DO', name: 'Dominican Republic', region: 'Americas', fakerLocale: 'es' },
  { code: 'EC', name: 'Ecuador', region: 'Americas', fakerLocale: 'es' },
  { code: 'SV', name: 'El Salvador', region: 'Americas', fakerLocale: 'es' },
  { code: 'GD', name: 'Grenada', region: 'Americas' },
  { code: 'GT', name: 'Guatemala', region: 'Americas', fakerLocale: 'es' },
  { code: 'GY', name: 'Guyana', region: 'Americas' },
  { code: 'HT', name: 'Haiti', region: 'Americas', fakerLocale: 'fr' },
  { code: 'HN', name: 'Honduras', region: 'Americas', fakerLocale: 'es' },
  { code: 'JM', name: 'Jamaica', region: 'Americas' },
  { code: 'MX', name: 'Mexico', region: 'Americas', fakerLocale: 'es_MX' },
  { code: 'NI', name: 'Nicaragua', region: 'Americas', fakerLocale: 'es' },
  { code: 'PA', name: 'Panama', region: 'Americas', fakerLocale: 'es' },
  { code: 'PY', name: 'Paraguay', region: 'Americas', fakerLocale: 'es' },
  { code: 'PE', name: 'Peru', region: 'Americas', fakerLocale: 'es' },
  { code: 'KN', name: 'Saint Kitts and Nevis', region: 'Americas' },
  { code: 'LC', name: 'Saint Lucia', region: 'Americas' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', region: 'Americas' },
  { code: 'SR', name: 'Suriname', region: 'Americas', fakerLocale: 'nl' },
  { code: 'TT', name: 'Trinidad and Tobago', region: 'Americas' },
  { code: 'US', name: 'United States', region: 'Americas', fakerLocale: 'en_US' },
  { code: 'UY', name: 'Uruguay', region: 'Americas', fakerLocale: 'es' },
  { code: 'VE', name: 'Venezuela', region: 'Americas', fakerLocale: 'es' },

  // ── Asia ─────────────────────────────────────────────────────────────────
  { code: 'AF', name: 'Afghanistan', region: 'Asia', fakerLocale: 'fa' },
  { code: 'AM', name: 'Armenia', region: 'Asia', fakerLocale: 'hy' },
  { code: 'AZ', name: 'Azerbaijan', region: 'Asia', fakerLocale: 'az' },
  { code: 'BH', name: 'Bahrain', region: 'Asia', fakerLocale: 'ar' },
  { code: 'BD', name: 'Bangladesh', region: 'Asia', fakerLocale: 'ur' },
  { code: 'BT', name: 'Bhutan', region: 'Asia' },
  { code: 'BN', name: 'Brunei', region: 'Asia' },
  { code: 'KH', name: 'Cambodia', region: 'Asia' },
  { code: 'CN', name: 'China', region: 'Asia', fakerLocale: 'zh_CN' },
  { code: 'CY', name: 'Cyprus', region: 'Asia', fakerLocale: 'el' },
  { code: 'GE', name: 'Georgia', region: 'Asia', fakerLocale: 'ka' },   // maps to fakerKA_GE
  { code: 'IN', name: 'India', region: 'Asia', fakerLocale: 'en_IN' },
  { code: 'ID', name: 'Indonesia', region: 'Asia', fakerLocale: 'id_ID' },
  { code: 'IR', name: 'Iran', region: 'Asia', fakerLocale: 'fa' },
  { code: 'IQ', name: 'Iraq', region: 'Asia', fakerLocale: 'ar' },
  { code: 'IL', name: 'Israel', region: 'Asia', fakerLocale: 'he' },
  { code: 'JP', name: 'Japan', region: 'Asia', fakerLocale: 'ja' },
  { code: 'JO', name: 'Jordan', region: 'Asia', fakerLocale: 'ar' },
  { code: 'KZ', name: 'Kazakhstan', region: 'Asia', fakerLocale: 'ru' },
  { code: 'KW', name: 'Kuwait', region: 'Asia', fakerLocale: 'ar' },
  { code: 'KG', name: 'Kyrgyzstan', region: 'Asia', fakerLocale: 'ru' },
  { code: 'LA', name: 'Laos', region: 'Asia' },
  { code: 'LB', name: 'Lebanon', region: 'Asia', fakerLocale: 'ar' },
  { code: 'MY', name: 'Malaysia', region: 'Asia' },
  { code: 'MV', name: 'Maldives', region: 'Asia' },
  { code: 'MN', name: 'Mongolia', region: 'Asia', fakerLocale: 'ru' },
  { code: 'MM', name: 'Myanmar', region: 'Asia' },
  { code: 'NP', name: 'Nepal', region: 'Asia', fakerLocale: 'ne' },
  { code: 'KP', name: 'North Korea', region: 'Asia', fakerLocale: 'ko' },
  { code: 'OM', name: 'Oman', region: 'Asia', fakerLocale: 'ar' },
  { code: 'PK', name: 'Pakistan', region: 'Asia', fakerLocale: 'ur' },
  { code: 'PS', name: 'Palestine', region: 'Asia', fakerLocale: 'ar' },
  { code: 'PH', name: 'Philippines', region: 'Asia', fakerLocale: 'tl' },
  { code: 'QA', name: 'Qatar', region: 'Asia', fakerLocale: 'ar' },
  { code: 'SA', name: 'Saudi Arabia', region: 'Asia', fakerLocale: 'ar' },
  { code: 'SG', name: 'Singapore', region: 'Asia', fakerLocale: 'en_SG' },
  { code: 'KR', name: 'South Korea', region: 'Asia', fakerLocale: 'ko' },
  { code: 'LK', name: 'Sri Lanka', region: 'Asia' },
  { code: 'SY', name: 'Syria', region: 'Asia', fakerLocale: 'ar' },
  { code: 'TW', name: 'Taiwan', region: 'Asia', fakerLocale: 'zh_TW' },
  { code: 'TJ', name: 'Tajikistan', region: 'Asia', fakerLocale: 'ru' },
  { code: 'TH', name: 'Thailand', region: 'Asia', fakerLocale: 'th' },
  { code: 'TL', name: 'Timor-Leste', region: 'Asia', fakerLocale: 'pt_PT' },
  { code: 'TM', name: 'Turkmenistan', region: 'Asia', fakerLocale: 'ru' },
  { code: 'AE', name: 'United Arab Emirates', region: 'Asia', fakerLocale: 'ar' },
  { code: 'UZ', name: 'Uzbekistan', region: 'Asia', fakerLocale: 'ru' },
  { code: 'VN', name: 'Vietnam', region: 'Asia', fakerLocale: 'vi' },
  { code: 'YE', name: 'Yemen', region: 'Asia', fakerLocale: 'ar' },

  // ── Europe ───────────────────────────────────────────────────────────────
  { code: 'AL', name: 'Albania', region: 'Europe' },
  { code: 'AD', name: 'Andorra', region: 'Europe', fakerLocale: 'es' },
  { code: 'AT', name: 'Austria', region: 'Europe', fakerLocale: 'de_AT' },
  { code: 'BY', name: 'Belarus', region: 'Europe', fakerLocale: 'ru' },
  { code: 'BE', name: 'Belgium', region: 'Europe', fakerLocale: 'nl_BE' },
  { code: 'BA', name: 'Bosnia and Herzegovina', region: 'Europe', fakerLocale: 'sr_RS_latin' },
  { code: 'BG', name: 'Bulgaria', region: 'Europe', fakerLocale: 'ru' },
  { code: 'HR', name: 'Croatia', region: 'Europe', fakerLocale: 'hr' },
  { code: 'CZ', name: 'Czech Republic', region: 'Europe', fakerLocale: 'cs_CZ' },
  { code: 'DK', name: 'Denmark', region: 'Europe', fakerLocale: 'da' },
  { code: 'EE', name: 'Estonia', region: 'Europe' },
  { code: 'FI', name: 'Finland', region: 'Europe', fakerLocale: 'fi' },
  { code: 'FR', name: 'France', region: 'Europe', fakerLocale: 'fr' },
  { code: 'DE', name: 'Germany', region: 'Europe', fakerLocale: 'de' },
  { code: 'GR', name: 'Greece', region: 'Europe', fakerLocale: 'el' },
  { code: 'HU', name: 'Hungary', region: 'Europe', fakerLocale: 'hu' },
  { code: 'IS', name: 'Iceland', region: 'Europe' },
  { code: 'IE', name: 'Ireland', region: 'Europe', fakerLocale: 'en_IE' },
  { code: 'IT', name: 'Italy', region: 'Europe', fakerLocale: 'it' },
  { code: 'XK', name: 'Kosovo', region: 'Europe' },
  { code: 'LV', name: 'Latvia', region: 'Europe', fakerLocale: 'lv' },
  { code: 'LI', name: 'Liechtenstein', region: 'Europe', fakerLocale: 'de_CH' },
  { code: 'LT', name: 'Lithuania', region: 'Europe' },
  { code: 'LU', name: 'Luxembourg', region: 'Europe', fakerLocale: 'fr_LU' },
  { code: 'MT', name: 'Malta', region: 'Europe' },
  { code: 'MD', name: 'Moldova', region: 'Europe', fakerLocale: 'ro' },
  { code: 'MC', name: 'Monaco', region: 'Europe', fakerLocale: 'fr' },
  { code: 'ME', name: 'Montenegro', region: 'Europe', fakerLocale: 'sr_RS_latin' },
  { code: 'NL', name: 'Netherlands', region: 'Europe', fakerLocale: 'nl' },
  { code: 'MK', name: 'North Macedonia', region: 'Europe', fakerLocale: 'mk' },
  { code: 'NO', name: 'Norway', region: 'Europe', fakerLocale: 'nb_NO' },
  { code: 'PL', name: 'Poland', region: 'Europe', fakerLocale: 'pl' },
  { code: 'PT', name: 'Portugal', region: 'Europe', fakerLocale: 'pt_PT' },
  { code: 'RO', name: 'Romania', region: 'Europe', fakerLocale: 'ro' },
  { code: 'RU', name: 'Russia', region: 'Europe', fakerLocale: 'ru' },
  { code: 'SM', name: 'San Marino', region: 'Europe', fakerLocale: 'it' },
  { code: 'RS', name: 'Serbia', region: 'Europe', fakerLocale: 'sr_RS_latin' },
  { code: 'SK', name: 'Slovakia', region: 'Europe', fakerLocale: 'sk' },
  { code: 'SI', name: 'Slovenia', region: 'Europe', fakerLocale: 'hr' },
  { code: 'ES', name: 'Spain', region: 'Europe', fakerLocale: 'es' },
  { code: 'SE', name: 'Sweden', region: 'Europe', fakerLocale: 'sv' },
  { code: 'CH', name: 'Switzerland', region: 'Europe', fakerLocale: 'de_CH' },
  { code: 'UA', name: 'Ukraine', region: 'Europe', fakerLocale: 'uk' },
  { code: 'GB', name: 'United Kingdom', region: 'Europe', fakerLocale: 'en_GB' },
  { code: 'VA', name: 'Vatican City', region: 'Europe', fakerLocale: 'it' },

  // ── Oceania ──────────────────────────────────────────────────────────────
  { code: 'AU', name: 'Australia', region: 'Oceania', fakerLocale: 'en_AU' },
  { code: 'FJ', name: 'Fiji', region: 'Oceania' },
  { code: 'KI', name: 'Kiribati', region: 'Oceania' },
  { code: 'MH', name: 'Marshall Islands', region: 'Oceania' },
  { code: 'FM', name: 'Micronesia', region: 'Oceania' },
  { code: 'NR', name: 'Nauru', region: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', region: 'Oceania', fakerLocale: 'en_NZ' },
  { code: 'PW', name: 'Palau', region: 'Oceania' },
  { code: 'PG', name: 'Papua New Guinea', region: 'Oceania' },
  { code: 'WS', name: 'Samoa', region: 'Oceania' },
  { code: 'SB', name: 'Solomon Islands', region: 'Oceania' },
  { code: 'TO', name: 'Tonga', region: 'Oceania' },
  { code: 'TV', name: 'Tuvalu', region: 'Oceania' },
  { code: 'VU', name: 'Vanuatu', region: 'Oceania', fakerLocale: 'fr' },
];

export const countriesByCode = Object.fromEntries(countries.map((c) => [c.code, c]));

export const getFlag = (code: string): string =>
  [...code.toUpperCase()]
    .map((c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('');
